version: 1.3.0
services:
  - composer:
      version: 2
  - mysql
  - php:
      version: 8.2
variables:
  global:
    COMPOSER_BIN: $SOURCE_DIR/vendor/bin
    BLT_DIR: $SOURCE_DIR/vendor/acquia/blt
cde-databases:
  - frost
events:
  build:
    steps:
      - setup-env:
          type: script
          script:
            - 'composer validate --no-check-all --ansi'
            - 'composer install --ansi'
            - 'source ${BLT_DIR}/scripts/pipelines/setup_env'
            - 'nvm install v12.13.0 --latest-npm'
            - 'npm install --global yarn'
      - validate:
          type: script
          script:
            - 'source ${BLT_DIR}/scripts/pipelines/validate'
      - setup-app:
          type: script
          script: # @see vendor/acquia/blt/scripts/pipelines/setup_app
            - 'set -ev'
            - 'export PATH=${COMPOSER_BIN}:$PATH'
            - 'blt source:build --no-interaction --ansi --verbose'
            - 'set +v'
      - drupal-sync:
          type: script
          script:
            - 'blt drupal:sync:default:db --no-interaction --verbose'
            - 'drush status-report' # Trigger a requirements check so public directories are generated before files.
            - 'blt drupal:sync:default:site --no-interaction --verbose'
      - tests:
          type: script
          script:
            - 'source ${BLT_DIR}/scripts/pipelines/tests'
      - build-artifact:
          type: script
          script:
            - 'source ${BLT_DIR}/scripts/pipelines/build_artifact'
  post-deploy:
    steps:
      - deploy:
          script:
            - pipelines-deploy
  pr-merged:
    steps:
      - deploy:
          script:
            - pipelines-deploy
  pr-closed:
    steps:
      - deploy:
          script:
            - pipelines-deploy
