<?php

/**
 * @file
 * Custom module to perform misc tasks.
 */

use Drupal\commerce_product\Entity\ProductType;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\node\Entity\NodeType;
use Drupal\node\NodeInterface;
use Drupal\taxonomy\Entity\Vocabulary;

/**
 * Helper function to get options (all or available).
 */
function _frost_custom_get_options() {
  return [
    'h1' => t('Heading 1'),
    'h2' => t('Heading 2'),
    'h3' => t('Heading 3'),
    'h4' => t('Heading 4'),
    'h5' => t('Heading 5'),
    'h6' => t('Heading 6'),
    'span' => t('Regular text'),
  ];
}

/**
 * Implements hook_page_attachments().
 */
function frost_custom_page_attachments(array &$attachments) {
  // Add an apple-touch-icon if there's one in the site root.
  if (file_exists(DRUPAL_ROOT . '/apple-touch-icon.png')) {
    $attachments['#attached']['html_head_link'][][] = [
      'rel' => 'apple-touch-icon',
      'href' => '/apple-touch-icon.png',
    ];
  }
}

/**
 * Implements hook_entity_extra_field_info().
 *
 * Adds a contextually-linked title, readmore line, and other pseudo-fields
 * to appropriate entity bundles.
 */
function frost_custom_entity_extra_field_info() {
  // The return array.
  $extra = [];

  // Ensure we only operate on install entity types.
  $entity_type_manager = \Drupal::service('entity_type.manager');
  $entity_definitions = $entity_type_manager->getDefinitions();

  // Go through all the product types and add extra fields for display.
  if (isset($entity_definitions['commerce_product'])) {
    foreach (ProductType::loadMultiple() as $bundle) {
      $extra['commerce_product'][$bundle->Id()] = [
        'display' => [
          'readmore' => [
            'label' => t('Read more link'),
            'description' => t('A link back to the entity that says read more.'),
            'weight' => 0,
          ],
          'checkoutalt' => [
            'label' => t('Checkout alternative'),
            'description' => t('A contact-us link for when we want commerce disabled.'),
            'weight' => 0,
          ],
        ],
      ];
    }
  }

  // Go through all the node types and add extra fields for display.
  if (isset($entity_definitions['node'])) {
    foreach (NodeType::loadMultiple() as $bundle) {
      $extra['node'][$bundle->Id()] = [
        'display' => [
          'frost_submitted' => [
            'label' => t('Submitted'),
            'description' => t('Author attribution for the content.'),
            'weight' => 0,
          ],
          'linked_title' => [
            'label' => t('Title (contextually linked)'),
            'description' => t('The title linked to the detail page.'),
            'weight' => 0,
          ],
        ],
      ];
    }
  }

  // Go through all the taxonomy vocabularies and add extra fields for display.
  if (isset($entity_definitions['taxonomy_term'])) {
    foreach (Vocabulary::loadMultiple() as $vocab) {
      $extra['taxonomy_term'][$vocab->Id()] = [
        'display' => [
          'linked_title' => [
            'label' => t('Title (contextually linked)'),
            'description' => t('The title linked to the detail page.'),
            'weight' => 0,
          ],
          'readmore' => [
            'label' => t('Read more link'),
            'description' => t('A link back to the entity that says read more.'),
            'weight' => 0,
          ],
        ],
      ];
    }
  }

  // Set pseudo-fields on users, which typically have the one bundle.
  if (isset($entity_definitions['user'])) {
    $extra['user']['user'] = [
      'display' => [
        'linked_title' => [
          'label' => t('Username (contextually linked)'),
          'description' => t('The title linked to the detail page.'),
          'weight' => 0,
        ],
      ],
    ];
  }

  return $extra;
}

/**
 * Implements hook_ENTITY_TYPE_view().
 *
 * Applies the pseudo-fields from frost_custom_entity_extra_field_info().
 */
function frost_custom_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  // Submitted line.
  if ($display->getComponent('frost_submitted')) {
    $sub = \Drupal::config('frost_custom.frost_submitted');
    $sub_line = 'Submitted by [node:author:name] on [node:created]';
    if ($sub->get($entity->bundle())) {
      $sub_line = $sub->get($entity->bundle());
    }
    $build['frost_submitted'] = [
      '#prefix' => '<div class="submitted">',
      '#markup' => \Drupal::token()
        ->replace($sub_line, ['node' => $entity]),
      '#suffix' => '</div>',
    ];
  }

  // Linked title.
  if ($display->getComponent('linked_title')) {
    $linked_title_url = Url::fromRoute('entity.node.canonical', ['node' => $entity->id()]);
    $attributes = [];
    $prefix = '<h2>';
    $suffix = '</h2>';

    if (in_array($view_mode, ['default', 'full', 'hero'])) {
      $prefix = '<h1 class="frost-custom-module--linked-title">';
      $suffix = '</h1>';
      $build['linked_title'] = [
        '#prefix' => $prefix,
        '#markup' => $entity->getTitle(),
        '#suffix' => $suffix,
      ];
    }
    else {
      $build['linked_title'] = [
        '#prefix' => $prefix,
        '#type' => 'link',
        '#url' => $linked_title_url,
        '#title' => $entity->getTitle(),
        '#attributes' => $attributes,
        '#suffix' => $suffix,
      ];
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_view().
 *
 * Applies the pseudo-fields from frost_custom_entity_extra_field_info().
 */
function frost_custom_taxonomy_term_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  // Linked title.
  if ($display->getComponent('linked_title')) {
    $linked_title_url = Url::fromRoute('entity.taxonomy_term.canonical', ['taxonomy_term' => $entity->id()]);
    $attributes = [];
    $prefix = '<h2>';
    $suffix = '</h2>';

    if (in_array($view_mode, ['default', 'full', 'hero'])) {
      $prefix = '<h1 class="frost-custom-module--linked-title">';
      $suffix = '</h1>';
      $build['linked_title'] = [
        '#prefix' => $prefix,
        '#markup' => $entity->getName(),
        '#suffix' => $suffix,
      ];
    }
    else {
      $build['linked_title'] = [
        '#prefix' => $prefix,
        '#type' => 'link',
        '#url' => $linked_title_url,
        '#title' => $entity->getName(),
        '#attributes' => $attributes,
        '#suffix' => $suffix,
      ];
    }
  }

  // Read more link.
  if ($display->getComponent('readmore')) {
    $link_url = Url::fromRoute('entity.taxonomy_term.canonical', ['taxonomy_term' => $entity->id()]);

    $build['readmore'] = [
      '#type' => 'link',
      '#title' => t('Learn more<span class="visually-hidden"> about @title</span>', [
        '@title' => $entity->getName(),
      ]),
      '#url' => $link_url,
      '#language' => $entity->language(),
      '#attributes' => [
        'rel' => 'tag',
        'title' => $entity->getName(),
        'class' => [
          'readmore-link',
          'border-top--1px-solid',
          'border-color--grey',
          'color--third',
          'display--block',
          'font-size--p75em',
          'font-weight--600',
          'margin-top--auto',
          'padding-vertical--4',
          'padding-horizontal--4',
          'text-align--center',
          'text-transform--uppercase',
        ],
      ],
    ];
  }
}

/**
 * Implements hook_ENTITY_TYPE_view().
 *
 * Applies the pseudo-fields from frost_custom_entity_extra_field_info().
 */
function frost_custom_commerce_product_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  // Read more link.
  if ($display->getComponent('readmore')) {
    $build['readmore'] = [
      '#type' => 'link',
      '#title' => t('Learn more<span class="visually-hidden"> about @title</span>', [
        '@title' => $entity->label(),
      ]),
      '#url' => $entity->toUrl(),
      '#language' => $entity->language(),
      '#attributes' => [
        'rel' => 'tag',
        'title' => $entity->label(),
        'class' => [
          'readmore-link',
          'border-top--1px-solid',
          'border-color--grey',
          'color--third',
          'display--block',
          'font-size--p75em',
          'font-weight--600',
          'margin-top--auto',
          'padding-vertical--4',
          'padding-horizontal--4',
          'text-align--center',
          'text-transform--uppercase',
        ],
      ],
    ];
  }

  // Checkout alt link.
  if ($display->getComponent('checkoutalt')) {
    $build['checkoutalt'] = [
      '#type' => 'link',
      '#title' => t('Contact sales<span class="visually-hidden"> about @title</span>', [
        '@title' => $entity->label(),
      ]),
      '#url' => $entity->toUrl(),
      '#language' => $entity->language(),
      '#attributes' => [
        'rel' => 'tag',
        'title' => $entity->label(),
        'class' => [
          'button',
        ],
      ],
    ];
  }
}

/**
 * Implements hook_ENTITY_TYPE_view().
 *
 * Applies the pseudo-fields from frost_custom_entity_extra_field_info().
 */
function frost_custom_user_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  // Linked title.
  if ($display->getComponent('linked_title')) {
    $title = $entity->getDisplayName();
    $prefix = '<h2>';
    $suffix = '</h2>';

    // Replace username with first and last name, if present.
    if (method_exists($entity, 'hasField')
      && $entity->hasField('field_name_first')
      && $entity->hasField('field_name_last')
    ) {
      $first_name = $entity->get('field_name_first')->value;
      $last_name = $entity->get('field_name_last')->value;
      $full_name = $first_name . ' ' . $last_name;
      if (mb_strlen($full_name) >= 3) {
        $title = $full_name;
      }
    }

    // We'll keep the 'linked' part out of users for now.
    if (in_array($view_mode, ['default', 'full', 'hero'])) {
      $prefix = '<h1 class="frost-custom-module--linked-title">';
      $suffix = '</h1>';
    }

    $build['linked_title'] = [
      '#prefix' => $prefix,
      '#markup' => $title,
      '#suffix' => $suffix,
    ];
  }
}

/**
 * Implements hook_node_links_alter().
 */
function frost_custom_node_links_alter(array &$links, NodeInterface $entity, array &$context) {
  $node_title_stripped = strip_tags($entity->label());

  // Attributes for the links container.
  $links['#attributes']['class'][] = 'flex--initial';
  $links['#attributes']['class'][] = 'margin-top--auto';
  $links['#attributes']['class'][] = 'border-top--1px-solid';
  $links['#attributes']['class'][] = 'border-color--grey';
  $links['#attributes']['class'][] = 'text-transform--uppercase';
  $links['#attributes']['class'][] = 'color--third';
  $links['#attributes']['class'][] = 'text-align--center';
  $links['#attributes']['class'][] = 'font-size--p75em';
  $links['#attributes']['class'][] = 'font-weight--600';
  $links['#attributes']['class'][] = 'list-style--none';

  // Theme out the readmore link specifically.
  $links['node']['#links']['node-readmore'] = [
    'title' => t('Learn more<span class="visually-hidden"> about @title</span>', [
      '@title' => $node_title_stripped,
    ]),
    'url' => $entity->toUrl(),
    'language' => $entity->language(),
    'attributes' => [
      'rel' => 'tag',
      'title' => $node_title_stripped,
      'class' => [
        'color--third',
        'display--block',
        'padding-vertical--4',
        'padding-horizontal--4',
      ],
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function frost_custom_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Add the SEO fields to the advanced fieldset.
  if (isset($form['advanced']) && isset($form['field_seo'])) {
    $form['field_seo']['#group'] = 'advanced';
  }
}

/**
 * Implements hook_local_tasks_alter().
 */
function frost_custom_local_tasks_alter(&$local_tasks) {
  if (isset($local_tasks)) {
    foreach ($local_tasks as $key => $task) {
      $keys = explode('.', $key);

      // Make tabs say 'Plan' instead of "Edit as Plan".
      if (in_array('form_mode_manager', $keys) && in_array('plan', $keys)) {
        $local_tasks[$key]['title'] = t('Plan');
      }
    }
  }
}
